# Generated by Django 6.0.5 on 2026-06-22 17:01

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papel', models.CharField(choices=[('ORGANIZADOR', 'Organizador'), ('VENDEDOR', 'Vendedor'), ('COMPRADOR', 'Comprador')], default='COMPRADOR', max_length=20)),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('cover', models.ImageField(upload_to='rifas/covers/%Y/%m/%d')),
                ('link_sorteio', models.URLField(blank=True, null=True)),
                ('qtd_numeros', models.IntegerField(default=100)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_sorteio', models.DateTimeField(blank=True, null=True)),
                ('finalizada', models.BooleanField(default=False)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rifas_criadas', to=settings.AUTH_USER_MODEL)),
                ('vendedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rifas_venda', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Premio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicao', models.IntegerField(help_text='Ex: 1 para Primeiro Lugar')),
                ('descricao', models.CharField(max_length=255)),
                ('rifa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premios', to='core.rifa')),
            ],
            options={
                'ordering': ['posicao'],
            },
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente de Pagamento'), ('PAGO', 'Aprovado / Pago'), ('EXPIRADO', 'Reserva Expirada')], default='PENDENTE', max_length=15)),
                ('data_compra', models.DateTimeField(auto_now_add=True)),
                ('comprovante', models.ImageField(blank=True, null=True, upload_to='comprovantes/%Y/%m/%d')),
                ('chave_pix', models.CharField(blank=True, max_length=255, null=True)),
                ('comprador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras', to=settings.AUTH_USER_MODEL)),
                ('vendedor_associado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendas_intermediadas', to=settings.AUTH_USER_MODEL)),
                ('rifa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras_rifa', to='core.rifa')),
            ],
        ),
        migrations.CreateModel(
            name='NumerosRifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('status', models.CharField(choices=[('DISPONIVEL', 'Disponível'), ('RESERVADO', 'Reservado'), ('PAGO', 'Pago')], default='DISPONIVEL', max_length=15)),
                ('compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='numeros_alocados', to='core.compra')),
                ('rifa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_numeros', to='core.rifa')),
            ],
            options={
                'ordering': ['numero'],
                'unique_together': {('rifa', 'numero')},
            },
        ),
    ]
