# Generated by Django 6.0.5 on 2026-06-22 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='chave_pix',
        ),
        migrations.AddField(
            model_name='compra',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
