# Generated by Django 6.0.5 on 2026-06-17 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rifa_link_sorteio_rifa_vendedor_alter_rifa_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='rifa',
            name='qtd_numeros',
            field=models.IntegerField(default=30),
        ),
    ]
