# Generated by Django 6.0.5 on 2026-06-22 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_compra_chave_pix_compra_cpf_delete_perfil'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rifa',
            name='ganhador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rifas_ganhas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rifa',
            name='numero_ganhador',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
