# Generated by Django 6.0.6 on 2026-06-22 19:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rifa_ganhador_rifa_numero_ganhador'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papel', models.CharField(choices=[('ORGANIZADOR', 'Organizador'), ('VENDEDOR', 'Vendedor Parceiro')], default='ORGANIZADOR', max_length=15)),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('organizador_vinculado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meus_vendedores', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VendedorRifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comissao_fixa', models.DecimalField(decimal_places=2, default=0.0, help_text='Valor fixo ganho por cada número pago', max_digits=6)),
                ('ativo', models.BooleanField(default=True)),
                ('rifa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendedores_associados', to='core.rifa')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rifas_permitidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('vendedor', 'rifa')},
            },
        ),
    ]
