# Generated by Django 6.0.6 on 2026-06-22 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_perfilusuario_vendedorrifa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(help_text='O e-mail não será exibido publicamente.', max_length=254)),
                ('texto', models.TextField()),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente de Moderação'), ('APROVADO', 'Aprovado e Público'), ('REJEITADO', 'Rejeitado / Oculto')], default='PENDENTE', max_length=15)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('rifa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='core.rifa')),
            ],
        ),
    ]
